name: Fedora

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}
    container: fedora:latest

    steps:
      - name: Installation
        run: |
          uname -a
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++
          dnf -y upgrade git
          dnf -y install perl
          dnf -y install libffi-devel
          dnf -y install zlib-devel
          dnf -y install libxft-dev
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake l ./scripts/test.lua -D -k ${{ matrix.kind }}


