name: Linux

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: tests
        run: |
          gcc --version
          sudo apt install gcc-10 g++-10
          export CC=gcc-10
          export CXX=gcc-10
          export LD=g++-10
          xmake l ./scripts/test.lua -D

